In [1]:
import tensorflow as tf

# Tensor
    * This is N-Dimentional representation of an array of data for various ranks like scalar (tensor0), vector (rank1), matrix (rank2), tensor (3 rank or more ...)

In [2]:
# scalar with tensor Rank = 0
tf.constant(10)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [3]:
# scalar with tensor rank = 0 , dtype = 'int8' (-128 to +127)
tf.constant(127, dtype = 'int8')

<tf.Tensor: shape=(), dtype=int8, numpy=127>

In [4]:
# scalar with tensor rank = 0, 'int16' => -32768 to +32767
const_1 = tf.constant(12768, dtype = 'int16')

In [5]:
const_1.numpy()

12768

In [6]:
const_1.shape

TensorShape([])

In [7]:
#### Vectors

# Vectors : Tensor Rank = 1 (Dimentionality = 1)
const_2 = tf.constant([20., 30., 40., 50., 60., 70., 15.],dtype = 'float16')
print(const_2)

tf.Tensor([20. 30. 40. 50. 60. 70. 15.], shape=(7,), dtype=float16)


In [10]:
import cv2
img_array = cv2.imread('pizza.jpg')

In [11]:
img_array.ravel()

array([238, 226, 220, ..., 239, 233, 234], dtype=uint8)

In [12]:
const_3 = tf.constant(img_array.ravel())


In [13]:
const_3

<tf.Tensor: shape=(2400000,), dtype=uint8, numpy=array([238, 226, 220, ..., 239, 233, 234], dtype=uint8)>

In [14]:
const_4 = tf.constant([[20, 30, 40, 50],
                       [120, 130, 140, 150],
                       [200, 300, 400, 500],
                       [220, 330, 440, 550]], dtype = 'float16')

In [15]:
print(const_4)

tf.Tensor(
[[ 20.  30.  40.  50.]
 [120. 130. 140. 150.]
 [200. 300. 400. 500.]
 [220. 330. 440. 550.]], shape=(4, 4), dtype=float16)


In [16]:
const_4.numpy()

array([[ 20.,  30.,  40.,  50.],
       [120., 130., 140., 150.],
       [200., 300., 400., 500.],
       [220., 330., 440., 550.]], dtype=float16)

In [17]:
const_4.shape

TensorShape([4, 4])

In [18]:
const_5 = tf.constant([[[20, 30, 40],
                       [120, 130, 140],
                       [200, 300, 400]],
                       
                       [[20, 30, 40],
                       [120, 130, 140],
                       [200, 300, 400]]], dtype = 'float16')

In [19]:
print(const_5)

tf.Tensor(
[[[ 20.  30.  40.]
  [120. 130. 140.]
  [200. 300. 400.]]

 [[ 20.  30.  40.]
  [120. 130. 140.]
  [200. 300. 400.]]], shape=(2, 3, 3), dtype=float16)


In [20]:
const_5.shape

TensorShape([2, 3, 3])

In [21]:
var_1 = tf.Variable([[[20, 30, 40],
                       [120, 130, 140],
                       [200, 300, 400]],
                       
                       [[20, 30, 40],
                       [120, 130, 140],
                       [200, 300, 400]]], dtype = 'float16')

In [22]:
print(var_1)

<tf.Variable 'Variable:0' shape=(2, 3, 3) dtype=float16, numpy=
array([[[ 20.,  30.,  40.],
        [120., 130., 140.],
        [200., 300., 400.]],

       [[ 20.,  30.,  40.],
        [120., 130., 140.],
        [200., 300., 400.]]], dtype=float16)>


In [23]:
# Y = WT * X + Bias
Weights = tf.Variable([[10],
                       [12],
                       [14],
                       [16],
                       [18],
                       [20],
                       [24]], dtype = 'float16')
print(Weights)

<tf.Variable 'Variable:0' shape=(7, 1) dtype=float16, numpy=
array([[10.],
       [12.],
       [14.],
       [16.],
       [18.],
       [20.],
       [24.]], dtype=float16)>


In [24]:

X = tf.Variable([[8],
                 [9],
                 [14],
                 [15],
                 [19],
                 [21],
                 [22]], dtype = 'float16')

In [25]:
# Y = WT * X
tf.tensordot(Weights, X, axes = 1)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [7,1], In[1]: [7,1] [Op:MatMul]

In [26]:
# Y = WT * X
WT = tf.transpose(Weights)
tf.tensordot(WT, X, axes = 1)

tf.tensordot(X, WT, axes = 1)

<tf.Tensor: shape=(7, 7), dtype=float16, numpy=
array([[ 80.,  96., 112., 128., 144., 160., 192.],
       [ 90., 108., 126., 144., 162., 180., 216.],
       [140., 168., 196., 224., 252., 280., 336.],
       [150., 180., 210., 240., 270., 300., 360.],
       [190., 228., 266., 304., 342., 380., 456.],
       [210., 252., 294., 336., 378., 420., 504.],
       [220., 264., 308., 352., 396., 440., 528.]], dtype=float16)>

In [27]:
# Y = X * WT
tf.tensordot(X, WT, axes = 1)

<tf.Tensor: shape=(7, 7), dtype=float16, numpy=
array([[ 80.,  96., 112., 128., 144., 160., 192.],
       [ 90., 108., 126., 144., 162., 180., 216.],
       [140., 168., 196., 224., 252., 280., 336.],
       [150., 180., 210., 240., 270., 300., 360.],
       [190., 228., 266., 304., 342., 380., 456.],
       [210., 252., 294., 336., 378., 420., 504.],
       [220., 264., 308., 352., 396., 440., 528.]], dtype=float16)>

In [28]:
# Dense Neural Network
from tensorflow.keras.layers import Dense
# Sequential Connections with Neural Network
from tensorflow.keras.models import Sequential
# Optimizers of Classifier
from tensorflow.keras.optimizers import Adam

In [29]:
def build_model():
    model = Sequential()
    # units = Number of Neurons , activation = 'relu', input_shape = shape of image (image height, image_width, dim)
    model.add(Dense(units = 16, activation = 'relu', input_shape = [100,100,3]))
    # Hidden Layer - I
    model.add(Dense(units = 32, activation = 'relu'))
    # Hidden Layer - II
    model.add(Dense(units = 64, activation = 'relu'))
    # Output layer - Binary Classification
    model.add(Dense(units = 1, activation = 'sigmoid'))
    # Model Compiler
    # Metrics = Check for model performance
    model.compile(loss='binary_crossentropy',optimizer='Adam', metrics = ['accuracy'])
    
    return model

model = build_model()

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100, 100, 16)      64        
                                                                 
 dense_1 (Dense)             (None, 100, 100, 32)      544       
                                                                 
 dense_2 (Dense)             (None, 100, 100, 64)      2112      
                                                                 
 dense_3 (Dense)             (None, 100, 100, 1)       65        
                                                                 
Total params: 2,785
Trainable params: 2,785
Non-trainable params: 0
_________________________________________________________________
